apiVersion: v1
kind: Pod
metadata:
  name: {{.Values.name}}
  namespace: {{.Values.namespace}}
spec:
  containers:
  - image: {{ .Values.containers.image }}:{{ .Values.containers.tag }}
    name: nginx 
    resources:
      limits:      
        memory: {{.Values.resources.limits.memory }}
        cpu: {{.Values.resources.limits.cpu }}  
