apiVersion: v1
kind: Pod
metadata:
  name: {{.Values.name}}
  namespace: {{.Values.namespace}}
spec:
  containers:
  - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
    name: redis
    ports:
    - containerPort: {{.Values.ports.containerPort}}
      protocol: {{.Values.ports.protocol}}
